In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Health analysis\ocd_patient_dataset.csv",keep_default_na=False)

In [13]:
df.head(10)

,Patient ID,Age,Gender,Ethnicity,Marital Status,Education Level,OCD Diagnosis Date,Duration of Symptoms (months),Previous Diagnoses,Family History of OCD,Obsession Type,Compulsion Type,Y-BOCS Score (Obsessions),Y-BOCS Score (Compulsions),Depression Diagnosis,Anxiety Diagnosis,Medications
0,1018,32,Female,African,Single,Some College,7/15/2016,203,MDD,No,Harm-related,Checking,17,10,Yes,Yes,SNRI
1,2406,69,Male,African,Divorced,Some College,4/28/2017,180,None,Yes,Harm-related,Washing,21,25,Yes,Yes,SSRI
2,1188,57,Male,Hispanic,Divorced,College Degree,2/2/2018,173,MDD,No,Contamination,Checking,3,4,No,No,Benzodiazepine
3,6200,27,Female,Hispanic,Married,College Degree,8/25/2014,126,PTSD,Yes,Symmetry,Washing,14,28,Yes,Yes,SSRI
4,5824,56,Female,Hispanic,Married,High School,2/20/2022,168,PTSD,Yes,Hoarding,Ordering,39,18,No,No,None
5,6946,32,Female,Asian,Married,College Degree,6/25/2016,46,GAD,No,Hoarding,Ordering,26,11,Yes,Yes,SSRI
6,9861,38,Female,Hispanic,Single,College Degree,3/13/2017,110,MDD,No,Contamination,Praying,12,16,Yes,No,SNRI
7,8396,57,Male,Hispanic,Divorced,College Degree,8/25/2015,197,PTSD,No,Religious,Ordering,31,4,Yes,No,SSRI
8,9039,36,Male,Hispanic,Divorced,College Degree,9/19/2016,84,None,No,Harm-related,Praying,37,24,No,Yes,None
9,1580,72,Female,Hispanic,Divorced,Graduate Degree,7/13/2014,47,GAD,Yes,Contamination,Ordering,28,36,Yes,Yes,Benzodiazepine

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Patient ID                     1500 non-null   int64
 1   Age                            1500 non-null   int64
 2   Gender                         1500 non-null   object
 3   Ethnicity                      1500 non-null   object
 4   Marital Status                 1500 non-null   object
 5   Education Level                1500 non-null   object
 6   OCD Diagnosis Date             1500 non-null   object
 7   Duration of Symptoms (months)  1500 non-null   int64
 8   Previous Diagnoses             1500 non-null   object
 9   Family History of OCD          1500 non-null   object
 10  Obsession Type                 1500 non-null   object
 11  Compulsion Type                1500 non-null   object
 12  Y-BOCS Score (Obsessions)      1500 non-null   int64
 13  Y-BOCS Score (Compulsions)     1500 non-null   int64
 14  Depression Diagnosis           1500 non-null   object
 15  Anxiety Diagnosis              1500 non-null   object
 16  Medications                    1500 non-null   object
dtypes: int64(5), object(12)
memory usage: 199.3+ KB

In [2]:
df.describe()

,Patient ID,Age,Duration of Symptoms (months),Y-BOCS Score (Obsessions),Y-BOCS Score (Compulsions)
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.00000
mean,5541.254000,46.781333,121.745333,20.048000,19.62600
std,2562.389469,16.830321,67.404610,11.823884,11.78287
min,1017.000000,18.000000,6.000000,0.000000,0.00000
25%,3338.000000,32.000000,64.000000,10.000000,9.00000
50%,5539.500000,47.000000,121.000000,20.000000,20.00000
75%,7745.500000,61.000000,178.000000,31.000000,29.00000
max,9995.000000,75.000000,240.000000,40.000000,40.00000

In [15]:
df.isnull().sum()

Patient ID                       0
Age                              0
Gender                           0
Ethnicity                        0
Marital Status                   0
Education Level                  0
OCD Diagnosis Date               0
Duration of Symptoms (months)    0
Previous Diagnoses               0
Family History of OCD            0
Obsession Type                   0
Compulsion Type                  0
Y-BOCS Score (Obsessions)        0
Y-BOCS Score (Compulsions)       0
Depression Diagnosis             0
Anxiety Diagnosis                0
Medications                      0
dtype: int64

In [17]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df.columns

Index(['patient_id', 'age', 'gender', 'ethnicity', 'marital_status',
       'education_level', 'ocd_diagnosis_date',
       'duration_of_symptoms_(months)', 'previous_diagnoses',
       'family_history_of_ocd', 'obsession_type', 'compulsion_type',
       'y-bocs_score_(obsessions)', 'y-bocs_score_(compulsions)',
       'depression_diagnosis', 'anxiety_diagnosis', 'medications'],
      dtype='object')

In [19]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

server = "LAPTOP-0GUJ766R\SQLEXPRESS"
database = "Health_Analysis"

driver = quote_plus("ODBC Driver 18 for SQL Server")

engine = create_engine(
    f"mssql+pyodbc://@{server}/{database}"
    f"?trusted_connection=yes"
    f"&driver={driver}"
    f"&TrustServerCertificate=yes"
)

# Write DataFrame to SQL Server
df.to_sql("health", engine, if_exists="replace", index=False)

# Read sample
pd.read_sql("SELECT TOP 5 * FROM customer;", engine)

C:\Users\muham\anaconda3\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1115.1'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

,patient_id,age,gender,ethnicity,marital_status,education_level,ocd_diagnosis_date,duration_of_symptoms_(months),previous_diagnoses,family_history_of_ocd,obsession_type,compulsion_type,y-bocs_score_(obsessions),y-bocs_score_(compulsions),depression_diagnosis,anxiety_diagnosis,medications
0,1018,32,Female,African,Single,Some College,7/15/2016,203,MDD,No,Harm-related,Checking,17,10,Yes,Yes,SNRI
1,2406,69,Male,African,Divorced,Some College,4/28/2017,180,None,Yes,Harm-related,Washing,21,25,Yes,Yes,SSRI
2,1188,57,Male,Hispanic,Divorced,College Degree,2/2/2018,173,MDD,No,Contamination,Checking,3,4,No,No,Benzodiazepine
3,6200,27,Female,Hispanic,Married,College Degree,8/25/2014,126,PTSD,Yes,Symmetry,Washing,14,28,Yes,Yes,SSRI
4,5824,56,Female,Hispanic,Married,High School,2/20/2022,168,PTSD,Yes,Hoarding,Ordering,39,18,No,No,None